import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

const branches: Record<string, string> = {
  dependent:"Confirm dependant route, care needs, travel-document readiness, and family-evidence questions. Source-link every immigration requirement.", school:"Record child age range, city, language, timing, and the official enrollment authority before comparing schools.", pet:"Record species, route, carrier constraints, and official veterinary/import authority. Keep veterinary evidence outside Markdown.", lost_document:"Contact the relevant issuing authority/consulate and follow its current official recovery path. Identity verification, declarations, police reports, and signatures are human-only.", urgent_abroad:"Prioritize immediate safety, emergency services where needed, lawful-stay status, accommodation, connectivity, and consular contact. Do not wait for research in an emergency."
};
function assertCase(directory: string) { const path = resolve(directory); if (!existsSync(path)) throw new Error(`CASE_NOT_FOUND: not a case directory: ${path}`); return path; }
export function createBranch(directory: string, kind: string, owner = "unknown") {
  const caseDir = assertCase(directory); if (!branches[kind]) throw new Error(`CASE_INVALID: unsupported branch kind: ${kind}`); if (owner !== "unknown" && !/^PERSON-\d{3,}$/.test(owner)) throw new Error("CASE_WRITE_REFUSED: owner must be a safe PERSON-* identifier or unknown");
  const output = join(caseDir, "resilience", `${kind}.md`); if (existsSync(output)) throw new Error(`CASE_WRITE_REFUSED: refusing to overwrite existing branch: ${output}`); mkdirSync(join(caseDir, "resilience"), { recursive:true });
  writeFileSync(output, `# Resilience branch — ${kind}\n\n- Owner: ${owner}\n- Status: not_started\n- Trigger: unknown\n- Created: unknown\n\n## Immediate safe steps\n\n- [ ] ${branches[kind]}\n- [ ] Add official sources as \`SRC-*\` and affected requirements as \`REQ-*\`.\n- [ ] Create consent-aware \`ACT-*\` records before any submission, booking, payment, or disclosure.\n- [ ] Store originals and receipts outside this Markdown file.\n\n## Current blocker\n\n- [ ] unknown\n`, "utf8"); return output;
}
export function createProviderComparison(directory: string, actionId: string, service: string, city: string) {
  const caseDir = assertCase(directory); if (!/^ACT-\d{3,}$/.test(actionId)) throw new Error("CASE_INVALID: action_id must look like ACT-001"); if (!service.trim() || !city.trim()) throw new Error("CASE_INVALID: service and city are required");
  const output = join(caseDir, "provider-comparisons", `${actionId}.md`); if (existsSync(output)) throw new Error(`CASE_WRITE_REFUSED: refusing to overwrite existing comparison: ${output}`); mkdirSync(join(caseDir, "provider-comparisons"), { recursive:true });
  writeFileSync(output, `# Provider comparison — ${service}\n\n- Linked action: ${actionId}\n- City/service area: ${city}\n- Retrieved: unknown\n- Decision: none\n\n## Candidate 1 — unknown\n\n- URL: unknown\n- Address/service area: unknown\n- Authorization evidence: unknown\n- Availability: unknown\n- Price: unknown\n- Turnaround: unknown\n- Cancellation terms: unknown\n- Language/format capability: unknown\n- Meets linked document chain: unknown\n- Excluded: no\n- Notes: unknown\n\n## Candidate 2 — unknown\n\n- URL: unknown\n- Address/service area: unknown\n- Authorization evidence: unknown\n- Availability: unknown\n- Price: unknown\n- Turnaround: unknown\n- Cancellation terms: unknown\n- Language/format capability: unknown\n- Meets linked document chain: unknown\n- Excluded: no\n- Notes: unknown\n\n## Proposal\n\n- Recommended candidate: unknown\n- Reason: unknown\n- Requires user confirmation before: booking, payment, document disclosure, or message sending\n`, "utf8"); return output;
}
